version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/sveltekit-test/build
hooks:
  BeforeInstall:
    - location: beforeinstall.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: afterinstall.sh
      timeout: 300
      runas: ec2-user